### ISSUE TITLE
Node.js support

### ISSUE THREAD

**Issue by timaschew** [rcarmo/piku#11]
First of all, very nice idea! Thanks for that.

I'm wondering if and how I can help to get Node.js support to piku.

**Comment by rcarmo** [comment]
Well, there are two components:

- Figuring out a sane way to do standalone Node environments
- Figuring out a way to do autodetection (package.json springs to mind)

So far I keep going up against another, more immediate concern, which is picking a Node version (am inclined to use Nodesource exclusively)...

**Comment by therocco** [comment]
Just a suggestion, but instead of picking a nodejs version it might be beneficial to use `nvm` so a developer can choose the version of node (if it is available on `nvm`) that supports their specific project.

**Comment by rcarmo** [comment]
I've started working on this, but got caught up in a little conundrum regarding passing ports to Node apps.

**Comment by rcarmo** [comment]
I've essentially given up on full isolation and have a "working" version that relies on whatever Ubuntu ships with the OS, but it's not documented yet and I'm trying to fix some assumptions regarding `Procfile` naming.

**Comment by IRobL** [comment]
Hi great work on this.  Is it possible to push an arbitrary dockerized app to Piku and skip any auto detection on the source code by simply detecting a Dockerfile and building an image out of that?

**Comment by rcarmo** [comment]
Possible? Sure. However, I have been putting that off for a number of reasons:

- that’s (a subset of) what dokku does, and piku was developed specifically for use in scenarios where I can’t use Docker, or where it would be forbiddingly expensive CPU-wise
- building images also means managing the entire lifecycle (cleaning out old images, etc.)
- I’d have to have radically different logic for restarting services (right now incron checks if there are any .ini file changes and nudges uwsgi, which is nice and neat and only happens _after_ I write out a service config, magically)
- I’d have to deal with network ports and re-jigger the nginx mapping, ports and whatnot, which is something I have kept simple on purpose

I use `docker-compose` a lot, though, so I might eventually get round to it, and I would be fine with taking a pull request for that (although I think we’d have to keep the Procfile as well unless a compose YAML was present, because app settings have to live someplace).
