### ISSUE TITLE
FriendlyARM install did not start piku.py on ssh login.

### ISSUE THREAD

**Issue by gintsgints** [rcarmo/piku#9]
I did everything to set up my Raspbery compatible device with piku. All went fine till last testing part.

When I log in to box it did not give me output you show at RASPBERRY_PI_QUICKSTART.md

After this I found that repository is not created at piku machine after push. I actually cannot push at all.
(response was there is no app/repository)

PS. Also there was problem with .ssh directory rights, but I did solve it.

**Comment by rcarmo** [comment]
That's most likely (still) due to permissions problems on the authorized_keys file itself, since that is what tells SSH to run piku.py. SSH is picky about such things, and you can try looking at the SSH logs to see if it complains, and why.

It might also help if you could provide more details on the Linux distribution (right now piku works on several flavors of Fedora/RHEL, Debian/Ubuntu, Arch and even FreeBSD, on ARM and Intel CPUs, so that may not be relevant, but I'm curious).

**Comment by gintsgints** [comment]
Good to know it is authorized_keys what does magic. :)
I did replace that entry with mine own. Because with original one it gave me:
```
: No such file or directory
Connection to ... closed.
```
Now have to check why it is so.

**Comment by gintsgints** [comment]
Ok. That's piku script who gives this:
```
piku@FriendlyARM:~$ ./piku.py
: No such file or directory
```

**Comment by gintsgints** [comment]
Works now.

When I did clone file on windows and copy it ower, it did put wrong line endings, and so executable piku.py was kind of wrong.

May be there is reason to update instructions so all needed files is cloned right to machine and not copied over to /tmp.
